### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by maehem** [ROBOTIS-GIT/Dynamixel2Arduino#32]
I was able to get Dynamixel2Arduino to work with ESP32 by making a custom SerialPortHandler that allowed me to re-assign the RX and TX pins on the ESP32.   Could you please consider integrating my simple changes into a future version of the library?

Also, I noticed that changing baud rates on the ESP32 can cause the ESP32 to hang.  But there is a special method to call for changing baud rate and I added that to my custom driver as well.

https://github.com/maehem/ESP32-Dynamixel

**Comment by OpusK** [comment]
Hi, @maehem 

> Could you please consider integrating my simple changes into a future version of the library?
Sure! Thanks for your contribution.

Since the style of esp32 is different from the existing Arduino core API, it seems that you have added a new constructor.
However, I think it would be better to fit the Arduino Core API as much as possible.

For example, a typical Arduino Serial does not have an API that allows users to assign rx and tx pins.
So, it would be better to call Serial.begin() from outside and treat it as a function that can only change the baud rate in porthandler.begin().
Or you may take the porthandler.begin(baudrate) function in the form begin(baudrate, rx = -1, tx = -1).

Either way, it would be nice if you PR for this repo :)

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
